{% set name = "uSockets-static" %}
{% set version = "0.6.0" %}
{% set sha256 = "999387d3653b2bc663c34aa7e973358ac4c4897dccd644553a5caab843a978a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/uNetworking/uSockets/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/uSockets.a  # [unix]

about:
  home: https://github.com/uNetworking/uSockets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "µSockets - miniscule networking & eventing"
  description: "This is the cross-platform async networking and eventing foundation library used by µWebSockets."
  doc_url: https://github.com/uNetworking/uSockets
  dev_url: https://github.com/uNetworking/uSockets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
