{% set name = "uWebSockets" %}
{% set version = "18.17.0" %}
{% set sha256 = "e2d2bd0e59bd6b544270aa348003fd4a42391015b4bf0eb54e0161ad108f913f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/uNetworking/uWebSockets/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
     - uSockets-static

test:
  commands:
    - test -d ${PREFIX}/include/uWebSockets  # [unix]
    - test -f ${PREFIX}/include/uWebSockets/App.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\uwebsocket\App.h (exit 1)  # [win]


about:
  home: https://github.com/uNetworking/uWebSockets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Simple, secure & standards compliant web server for the most demanding of applications."
  description: "µWebSockets is a simple to use yet thoroughly optimized, standards compliant and secure implementation of WebSockets (and HTTP). It comes with built-in pub/sub support, URL routing, TLS 1.3, SNI, IPv6, permessage-deflate and is battle tested as one of the most popular implementations, reaching many millions of end-users daily. It's currently juggling billions of USD in many popular Bitcoin exchanges, every day with outstanding real-world performance."
  doc_url: https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md
  dev_url: https://github.com/uNetworking/uWebSockets

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
