{% set name = "html5validator" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b926beb3b9c73c2fef337509f4f4f2f11d2596623d5b06ade9a8604b84e7db47

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - html5validator

about:
  home: https://github.com/svenkreiss/html5validator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Command line tool to validate HTML5 files. Great for continuous integration.'
  description: |
    html5validator is a command line tool that tests files for HTML5 validity. This was written with static site generators like Jekyll and Pelican in mind. Dynamic html content (for example from JS template engines) can be crawled (e.g. with localcrawl) and then validated.
  doc_url: https://github.com/svenkreiss/html5validator
  dev_url: https://github.com/svenkreiss/html5validator

extra:
  recipe-maintainers:
    - SylvainCorlay
