{% set name = "xeus-python-static" %}
{% set version = "0.8.0" %}
{% set commit = "e71c2096d57cdc0e75af05a6d34e58d3b0ce9ffc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-xeus/xeus-python-wheel/archive/{{ commit }}.tar.gz
  sha256: 514182b61a62793a1083363798832714c0475113993e5c9a890d846fda3f0486

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - nasm  # [win]
    - perl  # [win]
  host:
    - python
    - pip
    - scikit-build
    # perl is technically a build tool but OpenSSL's checks for its availability in host.
    - perl  # [win]
  run:
    - python

test:
  imports:
    - xpython_launcher

about:
  home: https://github.com/jupyter-xeus/xeus-python-wheel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A fully static build of xeus-python'
  description: 'xeus-python is a Jupyter kernel for Python based on the Xeus library.'
  doc_url: https://xeus-python.readthedocs.io/
  dev_url: https://github.com/jupyter-xeus/xeus-python-wheel

extra:
  recipe-maintainers:
    - SylvainCorlay
