{% set name = "vaex" %}
{% set version = "1.0.0b2" %}
{% set sha256 = "25e46cad930a06786de5f4d6a877c91280051f1d52ad9e2727863057f7387932" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.7.2
    - scipy >=0.1
    - astropy >=0.3
    - matplotlib >=1.3.1
    - h5py >=2.2.1
    - PyOpenGL>=3.1.0
    - jprops
    - aplus
    - tornado>4.1
    - futures>=2.2.0
    - future >= 0.15.2
    - pyyaml
    - kapteyn
    - cachetools
    - progressbar2
    - attrdict
    - psutil>=1.2.1
    - pandas
    - pillow

test:
    - vaex

about:
  home: http://vaex.astro.rug.nl
  license: MIT
  license_file: LICENSE.txt
  summary: 'Visualize and explore large tabular datasets using statistics on an N-dimensional grid'
  description: |
    Veax is a program (and Python library) to visualize and explore large tabular
    datasets using statistics on an N-dimensional grid. It mainly renders histograms,
    density plots and volume rendering plots for visualization in the order of 10e9 rows
    in the order of 1 second. For exploration it support selection in 1 and 2d, but it
    can also analyse the columns (dimensions) to find subspaces which are richer
    in information than others.
  doc_url: http://vaex.readthedocs.io/
  dev_url: https://github.com/maartenbreddels/vaex

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
