{% set name = "leocad" %}
{% set version = "19.07.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leozide/leocad/archive/v{{ version }}.tar.gz
  sha256: b74557e00366f1d3ddc211f9e55c28dba39987d66e5e3106490ab5fb75d25bc0
 
build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - libglu
    - {{ compiler('cxx') }}
    # Required to link with libGL
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
  host:
    - qt
    - ldraw-parts
    # Required to link with libGL
    - xorg-libxfixes                 # [linux]
  run:
    - ldraw-parts

test:
  commands:
    - test -f ${PREFIX}/bin/leocad

about:
  home: https://github.com/leozide/leocad
  license: GPL-2.0-only
  license_family: GPL
  license_file: docs/COPYING.txt
  summary: 'A CAD program for creating virtual LEGO models'
  description: |
    LeoCAD has an intuitive interface that is designed to allow
    new users to start creating new models without having to spend
    too much time learning the application.
    At the same time, it has a rich feature set that
    enables experienced users to build models by using
    techniques that are more advanced.
  doc_url: https://www.leocad.org/
  dev_url: https://www.leocad.org/

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wolfv
